version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    restart: 'no'
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=transport123
      - POSTGRES_DB=transport_ecosystem_management_db
    ports:
      - '5432:5432'
    volumes: 
      - /opt/pg_data:/var/lib/postgresql/data
      - ./sql:/tmp/sql

    network_mode: "host"

  adminer:
    image: adminer
    restart: 'no'
    ports:
      - 8080:8080

    network_mode: "host"
