version: '3.8'
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
      - ./sql:/tmp/sql
      
    environment:
      - MYSQL_ROOT_PASSWORD=transport123
      - MYSQL_PASSWORD=transport123
      - MYSQL_USER=db_user
      - MYSQL_DATABASE=transport_ecosystem_management_db

  adminer:
    image: adminer
    restart: 'no'
    ports:
      - 8080:8080
