version: '3.8'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/tmp/sql
      
    environment:
      - MYSQL_ROOT_HOST=mysql
      - MYSQL_ROOT_PASSWORD=transport123
      - MYSQL_PASSWORD=transport123
      - MYSQL_USER=db_user
      - MYSQL_DATABASE=transport_ecosystem_management_db
    
    extra_hosts:
      - "host.docker.internal:host-gateway"

  adminer:
    image: adminer
    restart: 'no'
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql-data:
    driver: local
