version: '3.8'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/tmp/sql
      
    environment:
      - MYSQL_ROOT_HOST=mysql
      - MYSQL_ROOT_PASSWORD=transport123
      - MYSQL_PASSWORD=transport123
      - MYSQL_USER=db_user
      - MYSQL_DATABASE=transport_ecosystem_management_db
    
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  phpmyadmin:
    image: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    restart: 'no'
    ports:
      - 8080:80
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
#  adminer:
#    image: adminer
#    restart: 'no'
#    ports:
#      - 8080:8080
#    extra_hosts:
#      - "host.docker.internal:172.17.0.1"

volumes:
  mysql-data:
    driver: local
