image_width: 1920
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1682.9403 ,    0.     ,  654.27492,
            0.     , 1688.02922,  401.41569,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.132717, -0.023410, 0.003325, -0.001348, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1721.01306,    0.     ,  652.32782,    0.     ,
            0.     , 1727.41101,  401.94248,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
